version: 0.0
os: linux
files:
  - source: /elevate
    destination: /elevate-prod/india/
    overwrite: true
  - source: /redirect.html
    destination: /elevate-prod/
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /elevate-prod/
    pattern: "**"
    owner: ec2-user
    group: nginx
    mode: 564
    mode: 775
    type:
      - file
  - object: /elevate-prod/
    pattern: "**"
    owner: ec2-user
    group: nginx
    mode: 564
    mode: 775
    type:
      - directory
